### Create User
POST http://localhost:4000/user
content-type: application/json

{
    "email": "test@mycloud.com",
    "username" : "test",
    "password" : "!Q2w3e4r"
}

### Find User
GET http://localhost:4000/user/test@mycloud.com

### Update User
PUT http://localhost:4000/user/ysh1
content-type: application/json

{
    "username": "sh",
    "password" : "test5555"
}

### Delete User
DELETE http://localhost:4000/user/ysh1